services:
  - type: web
    name: gesture-flask-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python sever.py
    envVars:
      - key: FLASK_ENV
        value: development
    autoDeploy: true
